apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-frontend-app
spec:
  destination:
    namespace: nodejs
    server: https://kubernetes.default.svc
  project: nodejs
  source:
    path: nodejs-persistent/frontend
    repoURL: https://github.com/welshstew/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: nodejs
        server: https://kubernetes.default.svc
      source:
        path: nodejs-persistent/frontend
        repoURL: https://github.com/welshstew/gitops-examples
        targetRevision: master
