apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-rbac
spec:
  destination:
    namespace: argocd-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/rbac/base
    repoURL: https://github.com/Purple-Sky-Pirates/openenv-cluster-config
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: argocd-gitops
        server: https://kubernetes.default.svc
      source:
        path: manifests/rbac/base
        repoURL: https://github.com/Purple-Sky-Pirates/openenv-cluster-config
        targetRevision: master
